### ISSUE TITLE
crontab -e  cannot write the weather.json.tmp and also weather.json

### ISSUE THREAD

**Issue by imchesterhk** [konrul/Pi-Kitchen-Dashboard#2]
Already added the line to cron like this
crontab -e
*/15 * * * * /var/www/html/Pi-Kitchen-Dashboard/bin/cron.sh

under data folder, can see the file weather.json.tmp generated every 15 mins, but the file is 0KB and nothing inside, if i manually run the cron.sh under bin folder, weather.json can be created successfully

Do you know what will cause this problem ? Thank you !

**Comment by konrul** [comment]
This is a Linux permissions question, it's not really a bug in P-K-D.

Delete the contents of the `data` directory. Ensure the cron user has write access to that directory, then run the `cron.sh` script and see what it creates.

**Comment by imchesterhk** [comment]
Thank you ! It is my fault ! after i reinstall the nodejs, all working fine now, thanks again !
